// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/replicamgr.proto

package replicamgrpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Shard struct {
	ShardId              uint64   `protobuf:"varint,1,opt,name=ShardId,proto3" json:"ShardId,omitempty"`
	IsLeader             bool     `protobuf:"varint,2,opt,name=IsLeader,proto3" json:"IsLeader,omitempty"`
	LeaderKey            string   `protobuf:"bytes,3,opt,name=LeaderKey,proto3" json:"LeaderKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shard) Reset()         { *m = Shard{} }
func (m *Shard) String() string { return proto.CompactTextString(m) }
func (*Shard) ProtoMessage()    {}
func (*Shard) Descriptor() ([]byte, []int) {
	return fileDescriptor_c791edbeb1c31eea, []int{0}
}

func (m *Shard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shard.Unmarshal(m, b)
}
func (m *Shard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shard.Marshal(b, m, deterministic)
}
func (m *Shard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shard.Merge(m, src)
}
func (m *Shard) XXX_Size() int {
	return xxx_messageInfo_Shard.Size(m)
}
func (m *Shard) XXX_DiscardUnknown() {
	xxx_messageInfo_Shard.DiscardUnknown(m)
}

var xxx_messageInfo_Shard proto.InternalMessageInfo

func (m *Shard) GetShardId() uint64 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *Shard) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *Shard) GetLeaderKey() string {
	if m != nil {
		return m.LeaderKey
	}
	return ""
}

type Replica struct {
	ReplicaName          string            `protobuf:"bytes,1,opt,name=ReplicaName,proto3" json:"ReplicaName,omitempty"`
	ShardMap             map[uint64]*Shard `protobuf:"bytes,2,rep,name=ShardMap,proto3" json:"ShardMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Replica) Reset()         { *m = Replica{} }
func (m *Replica) String() string { return proto.CompactTextString(m) }
func (*Replica) ProtoMessage()    {}
func (*Replica) Descriptor() ([]byte, []int) {
	return fileDescriptor_c791edbeb1c31eea, []int{1}
}

func (m *Replica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Replica.Unmarshal(m, b)
}
func (m *Replica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Replica.Marshal(b, m, deterministic)
}
func (m *Replica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Replica.Merge(m, src)
}
func (m *Replica) XXX_Size() int {
	return xxx_messageInfo_Replica.Size(m)
}
func (m *Replica) XXX_DiscardUnknown() {
	xxx_messageInfo_Replica.DiscardUnknown(m)
}

var xxx_messageInfo_Replica proto.InternalMessageInfo

func (m *Replica) GetReplicaName() string {
	if m != nil {
		return m.ReplicaName
	}
	return ""
}

func (m *Replica) GetShardMap() map[uint64]*Shard {
	if m != nil {
		return m.ShardMap
	}
	return nil
}

type ReplicaUpdateReq struct {
	ReplicaInfo          *Replica `protobuf:"bytes,1,opt,name=ReplicaInfo,proto3" json:"ReplicaInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaUpdateReq) Reset()         { *m = ReplicaUpdateReq{} }
func (m *ReplicaUpdateReq) String() string { return proto.CompactTextString(m) }
func (*ReplicaUpdateReq) ProtoMessage()    {}
func (*ReplicaUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c791edbeb1c31eea, []int{2}
}

func (m *ReplicaUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaUpdateReq.Unmarshal(m, b)
}
func (m *ReplicaUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaUpdateReq.Marshal(b, m, deterministic)
}
func (m *ReplicaUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaUpdateReq.Merge(m, src)
}
func (m *ReplicaUpdateReq) XXX_Size() int {
	return xxx_messageInfo_ReplicaUpdateReq.Size(m)
}
func (m *ReplicaUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaUpdateReq proto.InternalMessageInfo

func (m *ReplicaUpdateReq) GetReplicaInfo() *Replica {
	if m != nil {
		return m.ReplicaInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Shard)(nil), "replicamgrpb.Shard")
	proto.RegisterType((*Replica)(nil), "replicamgrpb.Replica")
	proto.RegisterMapType((map[uint64]*Shard)(nil), "replicamgrpb.Replica.ShardMapEntry")
	proto.RegisterType((*ReplicaUpdateReq)(nil), "replicamgrpb.ReplicaUpdateReq")
}

func init() {
	proto.RegisterFile("proto/replicamgr.proto", fileDescriptor_c791edbeb1c31eea)
}

var fileDescriptor_c791edbeb1c31eea = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x64, 0x5b, 0x6b, 0xdb, 0x17, 0x85, 0xb2, 0x6a, 0x09, 0x51, 0x24, 0xd4, 0x4b, 0xbc, 0x6c,
	0x20, 0x1e, 0x14, 0x2f, 0x82, 0x50, 0xb0, 0x56, 0x45, 0x56, 0x04, 0xd1, 0xd3, 0xa6, 0x79, 0x8d,
	0xd2, 0x8f, 0xac, 0xeb, 0x56, 0xc8, 0x9f, 0xf3, 0xb7, 0x49, 0x37, 0x9f, 0x85, 0xde, 0x66, 0x67,
	0xe7, 0xcd, 0xbc, 0xe1, 0x41, 0x5f, 0xaa, 0x44, 0x27, 0xbe, 0x42, 0x39, 0xff, 0x9a, 0x88, 0x45,
	0xac, 0x98, 0x21, 0xe8, 0x5e, 0xc5, 0xc8, 0xd0, 0x39, 0x8e, 0x93, 0x24, 0x9e, 0xa3, 0x6f, 0xfe,
	0xc2, 0xd5, 0xd4, 0xc7, 0x85, 0xd4, 0x69, 0x26, 0x1d, 0x7c, 0x40, 0xeb, 0xe5, 0x53, 0xa8, 0x88,
	0xda, 0xd0, 0x36, 0x60, 0x14, 0xd9, 0xc4, 0x25, 0xde, 0x0e, 0x2f, 0x9e, 0xd4, 0x81, 0xce, 0xe8,
	0xe7, 0x01, 0x45, 0x84, 0xca, 0x6e, 0xb8, 0xc4, 0xeb, 0xf0, 0xf2, 0x4d, 0x4f, 0xa0, 0x9b, 0xa1,
	0x31, 0xa6, 0x76, 0xd3, 0x25, 0x5e, 0x97, 0x57, 0xc4, 0xe0, 0x8f, 0x40, 0x9b, 0x67, 0xab, 0x50,
	0x17, 0xac, 0x1c, 0x3e, 0x89, 0x05, 0x9a, 0x8c, 0x2e, 0xaf, 0x53, 0xf4, 0x06, 0x3a, 0x26, 0xf2,
	0x51, 0x48, 0xbb, 0xe1, 0x36, 0x3d, 0x2b, 0x38, 0x63, 0xf5, 0x22, 0x2c, 0x17, 0xb3, 0x42, 0x35,
	0x5c, 0x6a, 0x95, 0xf2, 0x72, 0xc8, 0x79, 0x86, 0xfd, 0x8d, 0x2f, 0xda, 0x83, 0xe6, 0x0c, 0xd3,
	0xbc, 0xcf, 0x1a, 0xd2, 0x73, 0x68, 0xfd, 0x8a, 0xf9, 0x0a, 0x4d, 0x11, 0x2b, 0x38, 0xd8, 0x0c,
	0x30, 0xd3, 0x3c, 0x53, 0x5c, 0x37, 0xae, 0xc8, 0x60, 0x0c, 0xbd, 0x3c, 0xf4, 0x55, 0x46, 0x42,
	0x23, 0xc7, 0x6f, 0x7a, 0x59, 0x16, 0x19, 0x2d, 0xa7, 0x89, 0x31, 0xb7, 0x82, 0xa3, 0xad, 0x9b,
	0xf2, 0xba, 0x32, 0x78, 0x03, 0xa8, 0x44, 0xf4, 0xbe, 0xb4, 0xbe, 0x43, 0xa1, 0x74, 0x88, 0x42,
	0xd3, 0xd3, 0xad, 0x2e, 0x65, 0xb4, 0xd3, 0x67, 0xd9, 0x29, 0x59, 0x71, 0x4a, 0x36, 0x5c, 0x9f,
	0xf2, 0xb6, 0xff, 0x7e, 0x28, 0xc5, 0x64, 0x26, 0x62, 0xf4, 0xeb, 0x06, 0xe1, 0xae, 0xd1, 0x5d,
	0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x70, 0x04, 0xc6, 0x28, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReplicamgrClient is the client API for Replicamgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicamgrClient interface {
	ReplicaHeartbeat(ctx context.Context, in *ReplicaUpdateReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type replicamgrClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicamgrClient(cc grpc.ClientConnInterface) ReplicamgrClient {
	return &replicamgrClient{cc}
}

func (c *replicamgrClient) ReplicaHeartbeat(ctx context.Context, in *ReplicaUpdateReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/replicamgrpb.replicamgr/ReplicaHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicamgrServer is the server API for Replicamgr service.
type ReplicamgrServer interface {
	ReplicaHeartbeat(context.Context, *ReplicaUpdateReq) (*empty.Empty, error)
}

// UnimplementedReplicamgrServer can be embedded to have forward compatible implementations.
type UnimplementedReplicamgrServer struct {
}

func (*UnimplementedReplicamgrServer) ReplicaHeartbeat(ctx context.Context, req *ReplicaUpdateReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaHeartbeat not implemented")
}

func RegisterReplicamgrServer(s *grpc.Server, srv ReplicamgrServer) {
	s.RegisterService(&_Replicamgr_serviceDesc, srv)
}

func _Replicamgr_ReplicaHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicamgrServer).ReplicaHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicamgrpb.replicamgr/ReplicaHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicamgrServer).ReplicaHeartbeat(ctx, req.(*ReplicaUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Replicamgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "replicamgrpb.replicamgr",
	HandlerType: (*ReplicamgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicaHeartbeat",
			Handler:    _Replicamgr_ReplicaHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/replicamgr.proto",
}
